pipeline {
    agent any
    environment {
        dockerhub = credentials('DockerHub')
    }
    stages {
        stage('Docker Build') {
            steps {
                script {
                    sh "docker build -f 01/Dockerfile -t z0ckr3/homer-page:1.0.0-${BUILD_ID} --no-cache 01"
                }
            }
        }
        stage('Docker Login') {
            steps {
                sh "echo $dockerhub_PSW | docker login -u $dockerhub_USR --password-stdin"
            }
        }
        stage('Docker Push') {
            steps {
                script {
                    sh "docker push z0ckr3/homer-page:1.0.0-${BUILD_ID}"
                }
            }
        }
        stage('Docker Logout') {
            steps {
                sh 'docker logout'
            }
        }
    }
}
